# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.CharField(max_length=150, verbose_name='答案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '查询问题',
                'verbose_name_plural': '查询问题',
            },
        ),
        migrations.CreateModel(
            name='UserFavourable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.CharField(max_length=150, verbose_name='答案')),
            ],
            options={
                'verbose_name': '用户好评',
                'verbose_name_plural': '用户好评',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('question', models.CharField(max_length=300, verbose_name='问题')),
                ('answer', models.CharField(max_length=150, verbose_name='系统返回答案')),
                ('fb', models.CharField(max_length=300, null=True, verbose_name='反馈意见')),
                ('true_answer', models.CharField(max_length=300, null=True, verbose_name='修正后的答案')),
                ('is_modify', models.BooleanField(verbose_name='是否已修改答案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户差评',
                'verbose_name_plural': '用户差评',
            },
        ),
    ]
