# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='user',
        ),
    ]
