# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clusterRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10, verbose_name='\u7c7b\u522b')),
                ('question', models.CharField(max_length=300, verbose_name='\u95ee\u9898')),
                ('answer', models.CharField(max_length=150, verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u805a\u7c7b\u7ed3\u679c',
                'verbose_name_plural': '\u805a\u7c7b\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='preprocessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='\u95ee\u9898')),
                ('answer', models.CharField(max_length=150, verbose_name='\u7b54\u6848')),
            ],
            options={
                'verbose_name': '\u9884\u5904\u7406\u6570\u636e',
                'verbose_name_plural': '\u9884\u5904\u7406\u6570\u636e',
            },
        ),
    ]
