# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterres',
            name='question',
            field=models.CharField(max_length=500, verbose_name='\u95ee\u9898'),
        ),
        migrations.AlterField(
            model_name='preprocessdata',
            name='question',
            field=models.CharField(max_length=500, verbose_name='\u95ee\u9898'),
        ),
    ]
