# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='updateModel',
        ),
    ]
