# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181102_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
