# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QADisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='\u95ee\u9898')),
                ('answer', models.CharField(max_length=150, verbose_name='\u7b54\u6848')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u95ee\u7b54\u6570\u636e',
                'verbose_name_plural': '\u95ee\u7b54\u6570\u636e',
            },
        ),
    ]
