# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='\u94fe\u63a5')),
                ('flag', models.BooleanField(verbose_name='\u662f\u5426\u722c\u53d6')),
            ],
            options={
                'verbose_name': '\u722c\u53d6\u94fe\u63a5',
                'verbose_name_plural': '\u722c\u53d6\u94fe\u63a5',
            },
        ),
    ]
