# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_urldisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadisplay',
            name='update_time',
            field=models.CharField(max_length=100, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
