# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20181104_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldisplay',
            old_name='flag',
            new_name='is_crawled',
        ),
    ]
