# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20181104_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadisplay',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
