# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20181104_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='\u5e74\u4efd')),
                ('score', models.CharField(max_length=20, verbose_name='\u5206\u6570\u7ebf')),
            ],
            options={
                'verbose_name': '\u7edf\u8ba1\u6570\u636e',
                'verbose_name_plural': '\u7edf\u8ba1\u6570\u636e',
            },
        ),
    ]
