# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_statisticsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qadisplay',
            options={'verbose_name': '\u539f\u59cb\u95ee\u7b54\u6570\u636e', 'verbose_name_plural': '\u539f\u59cb\u95ee\u7b54\u6570\u636e'},
        ),
        migrations.AlterModelOptions(
            name='statisticsdata',
            options={'verbose_name': '\u4e0a\u4f20\u7edf\u8ba1\u6570\u636e', 'verbose_name_plural': '\u4e0a\u4f20\u7edf\u8ba1\u6570\u636e'},
        ),
    ]
